apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabric-bag-counter.fullname" . }}-api
  labels:
    {{- include "fabric-bag-counter.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.api.service.webrtcPort }}
      targetPort: webrtc
      protocol: TCP
      name: webrtc
  selector:
    {{- include "fabric-bag-counter.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
